openapi: 3.0.0
info:
  title: Mon API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login into the app
      requestBody:
        description: Données de l'utilisateur
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilisateur'
    post:
      summary: Créer un nouvel utilisateur
      requestBody:
        description: Données de l'utilisateur
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilisateur'
  /utilisateur/{id}:
    get:
      summary: Récupérer un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur
          schema:
            type: integer
      responses:
        '200':
          description: Succès
components:
  schemas:
    Utilisateur:
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        email:
          type: string
